## Basic ML Homework
### Модуль 4: Теоретический минимум для ML: линейная алгебра, начала мат.анализа

## 1. Линейная алгебра

1.1 Даны матрицы $A = \begin{pmatrix}
2 & −4 \\
3 & 5 \\
−1 & 0 
\end{pmatrix},
$
$B = \begin{pmatrix}1 & 2 & 7 \\ −3 & −4 & 0 \\ 5 & 2 & 1 \end{pmatrix}$, $C = \begin{pmatrix}
6 & −3 & 9 \\
4 & −5 & 2 \\
8 & 1 & 5
\end{pmatrix}.$

Посчитайте матрицу $D = A^{\top}C - 2A^{\top}B^{\top}$. Приведите полную последовательность вычислений.

$A^{\top} = \begin{pmatrix} 2 & 3 & -1 \\ −4 & 5 & 0 \end{pmatrix}
$
$B^{\top} = \begin{pmatrix}1 & -3 & 5 \\ 2 & −4 & 2 \\ 7 & 0 & 1 \end{pmatrix}$

Подставляем:
$D = \begin{pmatrix} 2 & 3 & -1 \\ −4 & 5 & 0 \end{pmatrix} * \begin{pmatrix} 6 & −3 & 9 \\ 4 & −5 & 2 \\ 8 & 1 & 5 \end{pmatrix} - 2 \begin{pmatrix} 2 & 3 & -1 \\ −4 & 5 & 0 \end{pmatrix} * \begin{pmatrix}1 & -3 & 5 \\ 2 & −4 & 2 \\ 7 & 0 & 1 \end{pmatrix} = \begin{pmatrix} 12 + 12 - 8  & -6-15-1 & 18 + 6 - 5 \\ −24+20 & 12-25 & -36+10 \end{pmatrix} - 2 * \begin{pmatrix} 2+6-7 & -6-12 & 10+6-1 \\ -4+10 & 12-20 & -20+10 \end{pmatrix} = \begin{pmatrix} 16 & -22 & 19 \\ −4 & -13 & -26 \end{pmatrix} - 2 * \begin{pmatrix} 1 & -18 & 15 \\ 6 & -8 & -10 \end{pmatrix} =  \begin{pmatrix} 14 & 14 & -11 \\ -16 & 3 & -6 \end{pmatrix}$

In [2]:
import numpy as np

In [3]:
A = np.array([[2,-4],[3,5],[-1,0]])
A
A.shape

(3, 2)

In [4]:
B = np.array([[1,2,7],[-3,-4,0], [5,2,1]])
B

array([[ 1,  2,  7],
       [-3, -4,  0],
       [ 5,  2,  1]])

In [5]:
C = np.array([[6,-3,9],[4,-5,2], [8,1,5]])
C

array([[ 6, -3,  9],
       [ 4, -5,  2],
       [ 8,  1,  5]])

In [6]:
𝐴.T

array([[ 2,  3, -1],
       [-4,  5,  0]])

In [7]:
B.T

array([[ 1, -3,  5],
       [ 2, -4,  2],
       [ 7,  0,  1]])

In [8]:
D = 𝐴.T.dot(C) - 2 * 𝐴.T.dot(B.T)
D

array([[ 14,  14, -11],
       [-16,   3,  -6]])

In [19]:
𝐴.T.dot(C)

array([[ 16, -22,  19],
       [ -4, -13, -26]])

1.2 Дано:

$ 3 \cdot \begin{pmatrix} x & 2 & 3 \\ −1 & y & 4 \end{pmatrix} +
2 \cdot \begin{pmatrix} 1 & 2 & −5 \\ 2 & −6 & z \end{pmatrix} =
\begin{pmatrix}
8 & v & −1 \\
1 & 6 & 4 \end{pmatrix}. $

Найдите значения $x$, $y$, $z$, и $v$.

$3*x + 2 = 8
$

$x = 2
$

$3*y - 12 = 6
$

$y = 6
$

$12 + 2*z = 4
$

$z = -4
$

$6 + 4 = v
$

$v = 10
$

1.3 На множестве $\mathbf{M}$ всех упорядоченных пар $(u; v)$ положительных чисел операции сложения и умножения введены
следующим образом:

$$
(u_1; v_1) + (u_2; v_2) = (u_1 \cdot u_2; v_1 \cdot v_2); 
λ(u; v) = (u^{\lambda}; v^{\lambda}),
$$

где $\lambda$ – вещественное число. Докажите, что при этом множество $\mathbf{M}$ становится линейным пространством. Выясните: а) какая пара играет роль нулевого элемента; б) какая пара является противоположной паре $(u; v)$; в) укажите размерность этого пространства и какой-нибудь его базис.

Для того чтобы показать, что множество 𝑀 является линейным пространством, необходимо проверить выполнение всех аксиом 
линейного пространства:

Аксиома коммутативности сложения:\
$
(u_1; v_1) + (u_2; v_2) = (u_1 \cdot u_2; v_1 \cdot v_2) = (u_2 \cdot u_1; v_2 \cdot v_1) = (u_2; v_2) + (u_1; v_1)
$\
Аксиома ассоциативности сложения:\
$
(u_1; v_1) + (u_2; v_2) + (u_3; v_3) = (u_1 \cdot u_2; v_1 \cdot v_2) + (u_3; v_3) = 
(u_1 \cdot u_2 \cdot u_3; v_1 \cdot v_2 \cdot v_3)  = (u_1; v_1) + (u_2 \cdot u_3; v_2 \cdot v_3)
$\
Аксиома существования нулевого элемента:\
нулевой элемент – это (1;1), так как (1;1) + (𝑢;𝑣) = (1⋅𝑢;1⋅𝑣) = (𝑢;𝑣) \ и \ (𝑢;𝑣) + (1;1) = (1⋅𝑢;1⋅𝑣) = (𝑢;𝑣).\
Аксиома существования противоположного элемента:\
противоположным элементом для (𝑢;𝑣) является (1/𝑢;1/𝑣), так как $(𝑢;𝑣) + (1/𝑢;1/𝑣) = (𝑢⋅1/𝑢;𝑣⋅1/𝑣) = 
(1;1) \ и \ (1/𝑢;1/𝑣) + (𝑢;𝑣) = (1;1).$\
Аксиома дистрибутивности умножения на скаляр: \
$𝜆(u_1; v_1) = (𝑢_1𝜆;𝑣_1𝜆) \ и \ (𝜆+𝜇)(𝑢_1;𝑣_1) = ((𝜆+𝜇)𝑢_1;(𝜆+𝜇)𝑣_1)$\
Аксиома дистрибутивности умножения на скаляр: \
$(𝜆𝜇)(𝑢;𝑣) = ((𝜆𝜇)𝑢;(𝜆𝜇)𝑣) \ и \ 𝜆((𝑢_1;𝑣_1) + (𝑢_2;𝑣_2)) = 𝜆(𝑢_1;𝑣_1) + 𝜆(𝑢_2;𝑣_2)$\
Таким образом, все аксиомы линейного пространства выполняются, следовательно, множество 𝑀 является линейным пространством.

а) Нулевым элементом является (1;1), так как (1;1) + (𝑢;𝑣) = (1⋅𝑢;1⋅𝑣) = (𝑢;𝑣) и (𝑢;𝑣) + (1;1) = (1⋅𝑢;1⋅𝑣) = (𝑢;𝑣).

б) Противоположной парой для (𝑢;𝑣) является (1/𝑢;1/𝑣), так как (𝑢;𝑣) + (1/𝑢;1/𝑣) = (𝑢⋅1/𝑢;𝑣⋅1/𝑣) = (1;1) 
и (1/𝑢;1/𝑣) + (𝑢;𝑣) = (1;1).

в) Размерность этого пространства равна 2, так как для любой упорядоченной пары (𝑢;𝑣) существует единственная линейная 
комбинация вида 𝜆(1;0) + 𝜇(0;1), где 𝜆 = 𝑢, 𝜇 = 𝑣. 
Размерность линейного пространства 𝑀 равна 2, так как любой вектор в 𝑀 можно представить в виде линейной комбинации пары векторов (1;0) и (0;1). Для этого нужно показать, что они линейно независимы и что любой вектор из 𝑀 можно представить в виде линейной комбинации этих векторов.
Линейная независимость: если 𝑎(1;0)+𝑏(0;1)=(0;0), то 𝑎=𝑏=0.\
Например:\
$e_1=(1,2)\ и \ e_2=(2,1)$ - базисные векторы \
Любой вектор $(𝑢;𝑣) = 𝜆_1(1;2) + 𝜆_2(2;1)$\
Пусть $𝜆_1=log_2{u}, 𝜆_2=log_2{v}$\
Следовательно, $(𝑢;𝑣)=log_2{u}{(1,2)}+ log_2{v}(2,1)=(1^{log_2{u}},2^{log_2{u}})+(2^{log_2{v}},1^{log_2{v}})=(1,u)+(v,1)=(u,v)$\
Т.о. размерность пространства М=2, посколько $e_1 \ и \ e_2$ - линейно независимые, а любой другой вариант линейно выражается через $e_1 \ и \ e_2$.

1.4 Докажите, что множество всех квадратных матриц второго порядка с известными операциями сложения и умножения на число образуют четырехмерное линейное пространство. Укажите какой-нибудь базис этого пространства.

Для того, чтобы доказать, что множество всех квадратных матриц второго порядка с операциями сложения и умножения на число образует четырехмерное линейное пространство, необходимо проверить выполнение следующих условий:\
Ассоциативность сложения: для любых матриц A, B и C размерности 2x2, выполняется равенство (A + B) + C = A + (B + C).\
Коммутативность сложения: для любых матриц A и B размерности 2x2, выполняется равенство A + B = B + A.\
Существование нулевого элемента: существует матрица O размерности 2x2, такая что A + O = A для любой матрицы A.\
Существование обратного элемента: для каждой матрицы A существует матрица B такая, что A + B = O, где O - нулевая матрица размерности 2x2.\
Ассоциативность умножения на число: для любых чисел a и b, и для любой матрицы A размерности 2x2, выполняется равенство a(bA) = (ab)A.\
Дистрибутивность умножения на число относительно сложения матриц: для любых чисел a и b, и для любых матриц A и B размерности 2x2, выполняется равенство a(A + B) = aA + aB и (a + b)A = aA + bA.\
Существование единичного элемента: существует матрица E размерности 2x2, такая что EA = A для любой матрицы A.\
Ассоциативность умножения матриц: для любых матриц A, B и C размерности 2x2, выполняется равенство A(BC) = (AB)C.\
Дистрибутивность умножения матриц относительно сложения матриц: для любых матриц A, B и C размерности 2x2, выполняется равенство A(B + C) = AB + AC и (A + B)C = AC + BC.

Все эти условия выполняются для множества всех квадратных матриц второго порядка, следовательно, это множество образует линейное пространство. 

Чтобы найти базис этого пространства, можно взять четыре линейно независимые матрицы размерности 2x2. Например:

Матрица E = [1 0; 0 1] - единичная матрица.\
Матрица A = [1 0; 0 0].\
Матрица B = [0 1; 0 0].\
Матрица C = [0 0; 1 0].\
Эти матрицы линейно независимы, так как ни одна из них не может быть выражена как линейная комбинация других. Кроме того, любая матрица размерности 2x2 может быть выражена как линейная комбинация этих четырех матриц.

Таким образом, {E, A, B, C} является базисом пространства всех квадратных матриц второго порядка

In [41]:
E = np.array([[1,0],[0,1]])
E 

array([[1, 0],
       [0, 1]])

In [42]:
A = np.array([[1,0],[0,0]])
A 

array([[1, 0],
       [0, 0]])

In [43]:
B = np.array([[0,1],[0,0]])
B 

array([[0, 1],
       [0, 0]])

In [44]:
C = np.array([[0,0],[1,0]])
C 

array([[0, 0],
       [1, 0]])

In [46]:
(A + B) + C == A + (B + C)

array([[ True,  True],
       [ True,  True]])

In [47]:
A + B == B + A

array([[ True,  True],
       [ True,  True]])

In [48]:
A + 0 == A

array([[ True,  True],
       [ True,  True]])

In [50]:
a = 2
b = 3
a*(b*A) == (a*b)*A

array([[ True,  True],
       [ True,  True]])

In [51]:
a*(A + B) == a*A + a*B

array([[ True,  True],
       [ True,  True]])

In [ ]:
 (a + b)*A == a*A + b*A

In [52]:
E*A == A

array([[ True,  True],
       [ True,  True]])

In [54]:
A*(B*C) == (A*B)*C

array([[ True,  True],
       [ True,  True]])

In [56]:
A*(B + C) == A*B + A*C

array([[ True,  True],
       [ True,  True]])

In [55]:
(A + B)*C == A*C + B*C

array([[ True,  True],
       [ True,  True]])

1.5 Укажите те значения параметров $p$ и $q$, при которых
ранг матрицы $A = \begin{pmatrix} 1 & 2 & 3 \\ 3 & 6 & p \\ 5 & 10 & q \end{pmatrix}$ равен единице.

$2*p - 3*6 = 0
$

$p = 9
$

$6*q - 10*p = 0
$

$q = 15
$

Ранг $1$

1.6 Относительно канонического базиса в $\mathbb{R}^2$ даны три вектора $f_1 = (2, −5)$, $f_2 = (−1, 3)$, $x = (1, −4)$. Докажите, что векторы $f_1$ и $f_2$ можно принять за новый базис, и найдите координаты вектора $x$ в этом базисе

$F^{-1}= 1/detF * (F^*)^{\top}$

$f_1$ и $f_2$ линейно независимые, следовательно, могут быть приняты в качестве базиса пространства $\mathbb{R}^2$

$F = \begin{pmatrix} 2 & -1 \\ -5 & 3 \end{pmatrix}$

$detF = 2*3 - (-1) *(-5) = 1
$

$F11= (-1)^2 * 3 = 3$ \
$F12= (-1)^3 * (-1) = 1$\
$F21= (-1)^3 * (-5) = 5$\
$F22= (-1)^4 * 2 = 2$ \
$F^* = \begin{pmatrix} 3 & 1 \\ 5 & 2 \end{pmatrix}$

Подставляем:

$F = 1/1 * \begin{pmatrix} 3 & 1 \\ 5 & 2 \end{pmatrix}^{\top} = \begin{pmatrix} 3 & 5 \\ 1 & 2 \end{pmatrix}$

Находим координаты вектора $x = (1, −4)$ относительно нового базиса:

$x_{new} = \begin{pmatrix} 1 & -4 \end{pmatrix} * \begin{pmatrix} 3 & 5 \\ 1 & 2 \end{pmatrix} = \begin{pmatrix} -1 & -3 \end{pmatrix}$

In [26]:
F = np.array([[2,-1],[-5,3]])
F

array([[ 2, -1],
       [-5,  3]])

In [27]:
det = np.linalg.det(F)
det

1.0000000000000002

In [33]:
F1 = np.array([[3,5],[1,2]])
F1

array([[3, 5],
       [1, 2]])

In [34]:
x = np.array([1,-4])
x

array([ 1, -4])

In [35]:
X = F1.T.dot(x) 
X

array([-1, -3])

1.7 Предположим, что существует линейный оператор, выраженный в базисе $(e_1, e_2)$ в виде матрицы $A = \begin{pmatrix} 1 & 0 \\ 0 & 2 \end{pmatrix}$. Найдите матрицу данного оператора в базисе из векторов $(\tilde{e}_1, \tilde{e}_2)$, если:

$$
\begin{cases}
\tilde{e}_1 = -2e_1 + 5e_2 \\
\tilde{e}_2 = -e_1 + 2e_2
\end{cases}.
$$

$A_{new}=E^{-1}*A*E$

$E^{-1}= 1/detE * (E^*)^{\top}$

$E = \begin{pmatrix} -2 & -1 \\ 5 & 2 \end{pmatrix}$

$detE = -4+5 = 1
$

$E11= (-1)^2 * 2 = 2$ \
$E12= (-1)^3 * 5 = -5$\
$E21= (-1)^3 * (-1) = 1$\
$E22= (-1)^4 * (-2) = -2$ \
$E^* = \begin{pmatrix} 2 & -5 \\ 1 & -2 \end{pmatrix}$\
Подставляем:\
$A_{new}=1/1*{\begin{pmatrix} 2 & -5 \\ 1 & -2 \end{pmatrix}}^{\top}*\begin{pmatrix} 1 & 0 \\ 0 & 2 \end{pmatrix}*\begin{pmatrix} -2 & -1 \\ 5 & 2 \end{pmatrix} ={\begin{pmatrix} 2 & 1 \\ -5 & -2 \end{pmatrix}}*\begin{pmatrix} 1 & 0 \\ 0 & 2 \end{pmatrix}*\begin{pmatrix} -2 & -1 \\ 5 & 2 \end{pmatrix} = \begin{pmatrix} 2 & 2 \\ -5 & -4\end{pmatrix}*\begin{pmatrix} -2 & -1 \\ 5 & 2 \end{pmatrix}=\begin{pmatrix} -4+10 & -2+4 \\ 10-20 & 5-8\end{pmatrix} =\begin{pmatrix} 6 & 2 \\ -10 & -3 \end{pmatrix}$

In [3]:
E = np.array([[-2,-1],[5,2]])
E

array([[-2, -1],
       [ 5,  2]])

In [4]:
det = np.linalg.det(E)
det

0.9999999999999998

In [5]:
E1 = np.array([[2,-5],[1,-2]])
E1

array([[ 2, -5],
       [ 1, -2]])

In [6]:
A = np.array([[1,0],[0,2]])
A

array([[1, 0],
       [0, 2]])

In [8]:
A_new = 1 * E1.T.dot(A).dot(E)
A_new

array([[  6,   2],
       [-10,  -3]])

## 2. Начала математического анализа

1. Найти матрицу Гессе следующей функции:
$$
    f(x,y) = x^3 - 2xy + y^2 - 3x - 2y.
$$

    Доп.задание (явно в курсе не обсуждалось): найдите точки локального экстремума функции $f$.

$
 \frac{\partial f(x)}{\partial x} = 3x^2 - 2y + 0 - 3 - 0 = 3x^2 - 2y - 3.
$

$
 \frac{\partial f(y)}{\partial y} = 0 - 2x + 2y + 0 - 0 - 2 = 2y - 2x - 2.
$

Решим систему:

$
\begin{cases}
3x^2 - 2y - 3 = 0 \\
2y - 2x - 2 = 0   
\end{cases}.
$

$
след.   y = x + 1
$

$
3x^2 - 2(x + 1) - 3 = 0
$

$
3x^2 - 2x - 5 = 0
$

$
x1 = 5/3 , x2 = -1
$

$
y1 = 8/3, y2 = 0
$

$
M1 (-1, 0) , M2 (5/3, 8/3)
$

$
 \frac{\partial^2 f(x)}{\partial x^2} = 6x
$

$
 \frac{\partial^2 f(x)}{\partial y^2} = -2
$

$
 \frac{\partial^2 f(y)}{\partial x^2} = -2
$

$
 \frac{\partial^2 f(y)}{\partial y^2} = 2
$

$ H1 \begin{pmatrix} -6 & -2 \\ −2 & 2\end{pmatrix}
H2 \begin{pmatrix} 10 & -2 \\ −2 & 2\end{pmatrix}
$
 
$для \ H1:
D1 = a11 < 0, D2 = |-6 * 2 - 4| = - 16 < 0 
$

$ для \ H2:
D1 = a11 > 0, D2 = |10 * 2 - 4| =  16 > 0
$

$
Функция \ имеет \ локальный \ минимум \ в \ точке \ M2 \ (5/3, 8/3)
$

In [9]:
from sympy import *

In [10]:
x = Symbol('x')
y = Symbol('y')

In [14]:
f = x**3-2*x*y+y**2-3*x-2*y

In [15]:
derivative_f = f.diff(x)
derivative_f

3*x**2 - 2*y - 3

In [16]:
derivative_f = f.diff(y)
derivative_f

-2*x + 2*y - 2

2. Проверьте, что функция $f = \ln(\sqrt{x} + \sqrt{y})$ удовлетворяет уравнению:

$$
x \frac{\partial f}{\partial x} + y \frac{\partial f}{\partial y} = \frac{1}{2}.
$$

$
\frac{\partial f}{\partial x} = \frac{1}{2\sqrt{x}\sqrt{y} + 2x}
$

$
\frac{\partial f}{\partial y} = \frac{1}{2\sqrt{x}\sqrt{y} + 2y}
$

$Подставляем \ в \ уравнение
$

$
x \frac{1}{2\sqrt{x}\sqrt{y} + 2x} + y \frac{1}{2\sqrt{x}\sqrt{y} + 2y} = \frac{1}{2}.
$

$
2y(2\sqrt{x}\sqrt{y} + 2x) + 2x(2\sqrt{x}\sqrt{y} + 2y) = (2\sqrt{x}\sqrt{y} + 2x) (2\sqrt{x}\sqrt{y} + 2y)
$

$
4y\sqrt{x}\sqrt{y} + 4x\sqrt{x}\sqrt{y} + 8xy = 4y\sqrt{x}\sqrt{y} + 4x\sqrt{x}\sqrt{y} + 8xy
$

$
0 = 0
$

$
Данная \ функция \ удовлетворяет \ данному \ уравнению.
$

3. Используя правило для вычисления производной сложной функции, найдите полный дифференциал $\frac{df}{dt}$, если $$f = e^{xy}\ln(x+y), \quad x = 2t^2, \quad y = 1 - 2t^2 .$$

$\frac{df}{dt}=\frac{df}{dx}\frac{dx}{dt} + \frac{df}{dy}\frac{dy}{dt}$, 

$\frac{df}{dx}=\frac{e^{xy}xy\ln(x+y)+ e^{xy}y^2\ln(x+y)+ e^{xy}}{x+y}
$

$\frac{dx}{dt}=4t
$

$\frac{df}{dy}=\frac{e^{xy}xy\ln(x+y)+ e^{xy}x^2\ln(x+y)+ e^{xy}}{x+y}
$

$\frac{dy}{dt}=-4t
$

$Подставляем:
$

$
\frac{df}{dt}= \frac{e^{xy}xy\ln(x+y)+ e^{xy}y^2\ln(x+y)+ e^{xy}}{x+y}\ 4t - \frac{e^{xy}xy\ln(x+y)+ e^{xy}x^2\ln(x+y)+ e^{xy}}{x+y}\ 4t = 4t\ e^{xy}\ln(x+y)\frac{y^2-x^2}{x+y}
$



In [39]:
x = Symbol('x')
y = Symbol('y')

In [ ]:
derivative_f = f.diff(x)
derivative_f

4. Предположим, задана функция $f: \mathbb{R}^3 \rightarrow \mathbb{R}^2$

$$
    f(x,y,z) = (x+y+z, xyz).
$$

   Найдите матрицу Якоби функции $f$, и её численное значение в точке $v = (1, 2, 3)$.

$J = \begin{pmatrix} \frac{\partial f1}{\partial x} & \frac{\partial f1}{\partial y} &  \frac{\partial f1}{\partial z} \\  \frac{\partial f3}{\partial x} & \frac{\partial f2}{\partial y} &  \frac{\partial f2}{\partial z} \end{pmatrix} = \begin{pmatrix} \ {1}&{1}&{1} \\ {yz}&{xz}&{xy}\end{pmatrix} = \begin{pmatrix} \ {1}&{1}&{1} \\ {6}&{3}&{2}\end{pmatrix}$